package com.eduforum.api.domain.assessment.dto.feedback;

import com.eduforum.api.domain.assessment.entity.FeedbackType;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.OffsetDateTime;
import java.util.Map;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Feedback response")
public class FeedbackResponse {

    @Schema(description = "Feedback ID", example = "1")
    private Long id;

    @Schema(description = "Student ID", example = "1")
    private Long studentId;

    @Schema(description = "Course ID", example = "1")
    private Long courseId;

    @Schema(description = "Submission ID", example = "1")
    private Long submissionId;

    @Schema(description = "Feedback type")
    private FeedbackType feedbackType;

    @Schema(description = "Title")
    private String title;

    @Schema(description = "Content")
    private String content;

    @Schema(description = "Is AI generated", example = "true")
    private Boolean isAiGenerated;

    @Schema(description = "Generated by", example = "2")
    private Long generatedBy;

    @Schema(description = "Metadata")
    private Map<String, Object> metadata;

    @Schema(description = "Is read", example = "false")
    private Boolean isRead;

    @Schema(description = "Read at")
    private OffsetDateTime readAt;

    @Schema(description = "Sent at")
    private OffsetDateTime sentAt;
}
